### ISSUE TITLE
V2ray 只能PC端使用，移动端可以连接，但是无法使用，请问可能是什么问题

### ISSUE THREAD

**Issue by qingfengfenga** [v2fly/v2ray-step-by-step#274]
## 与 bug 有关的页面 / related page
[wss_and_web.md.md](https://github.com/v2fly/v2ray-step-by-step/blob/transifex/zh_CN/advanced/wss_and_web.md)

## bug 描述 / description of the bug
参考以上文档，只做了容器化（v2ray+nginx 两个host模式容器），证书替换为阿里云的免费证书

Win/Mac客户端可以正常连接使用（V2rayN和V2rayU），移动端 安卓/IOS/Quest2 都可以连接，但是都无法使用（几乎所有主流的客户端和多个网络都试了）

想请问一下这种情况怎么排查，可能是什么问题，比如内核版本、客户端版本、加密方式、TLS版本等

## 复现步骤 / how we can reproduce
在此描述复现出现的问题所需的步骤和环境。

服务端配置文件

```
{
  "inbounds": [
    {
      "port": 10000,
      "listen":"127.0.0.1",//只监听 127.0.0.1，避免除本机外的机器探测到开放了 10000 端口
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "xxx",
            "alterId": 0
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
        "path": "/ray"
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}

```

安装后生成的客户端配置文件
```
{
  "inbounds": [
    {
      "port": 1080,
      "listen": "127.0.0.1",
      "protocol": "socks",
      "sniffing": {
        "enabled": true,
        "destOverride": ["http", "tls"]
      },
      "settings": {
        "auth": "noauth",
        "udp": false
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxx",
            "port": 443,
            "users": [
              {
                "id": "xxx",
                "alterId": 64
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "security": "tls",
        "wsSettings": {
          "path": "/ray"
        }
      }
    }
  ]
}

```

可用的 V2rayN配置
![image](https://user-images.githubusercontent.com/41416092/196088130-cfa7a457-e586-4c14-b137-5d738e030061.png)

服务端没有报错日志
```
V2Ray 4.45.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.3 linux/amd64)
A unified platform for anti-censorship.
2022/08/08 09:30:35 [Info] main/jsonem: Reading config: /etc/v2ray/config.json
2022/08/08 09:30:35 [Warning] V2Ray 4.45.2 started
V2Ray 4.45.2 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.18.3 linux/amd64)
A unified platform for anti-censorship.
2022/08/08 09:31:28 [Info] main/jsonem: Reading config: /etc/v2ray/config.json
2022/08/08 09:31:28 [Warning] V2Ray 4.45.2 started

```

docker-compose.yaml

```
version: "3"

services:

  nginx:
    image: nginx:1.23.1-alpine
    restart: always
    container_name: nginx
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/logs:/var/log/nginx
      #- ./nginx/www:/usr/share/nginx/html/www

  v2ray:
    image: v2fly/v2fly-core:v4.45.2
    restart: always
    container_name: v2ray
    network_mode: host
    volumes:
      - ./v2ray:/etc/v2ray

```
